--drop table commands

DROP TABLE VOTE_COMMENTS;
DROP TABLE CLASSIFIEDBY;
DROP TABLE TOPIC;
DROP TABLE VOTE_POST;
DROP TABLE WRITE_COMMENTS;
DROP TABLE CONTAINS_COMMENTS;
DROP TABLE POST_WRITEPOST;
DROP TABLE REGISTERED_USER;
